language: generic
sudo: required
services:
    - docker

before_install:
  - docker build -t lawrenceyeh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lawrenceyeh/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-624139534533"
  buctet_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY