language: generic
sudo: required
services:
    - docker

before_install:
  - docker build -t lawrenceyeh/docker-react -f Dockerfile.dev .

script:
  - docker run lawrenceyeh/docker-react npm run test -- --coverage